# generated by dbconfig-common

# map from dbconfig-common database types to their names as known by RT
my %typemap = (
    mysql   => 'mysql',
    pgsql   => 'Pg',
    sqlite3 => 'SQLite',
);
    
Set($DatabaseType, $typemap{@db_type@} || "UNKNOWN");

Set($DatabaseHost, '@db_host@');
Set($DatabasePort, '@db_port@');

Set($DatabaseUser , '@db_user@');
Set($DatabasePassword , '@db_password@');

# SQLite needs a special case, since $DatabaseName must be a full pathname
my $dbc_dbname = '@db_name@'; if ( "$DatabaseType" eq "sqlite3" ) { Set ($DatabaseName, '/var/lib/dbconfig-common/sqlite3/request-tracker4' . '/' . $dbc_dbname); } else { Set ($DatabaseName, $dbc_dbname); }
